import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        height: height * 0.35,
        justifyContent: "flex-start",
        paddingTop: Platform.OS === "ios" ? 60 : 40,
    },
    headerTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
        marginBottom: 20,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "900",
        color: "white",
        letterSpacing: 1,
        flex: 1,
        marginHorizontal: 16,
        textAlign: "center",
    },
    headerActions: {
        flexDirection: "row",
        gap: 8,
    },
    headerActionButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    summaryCard: {
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        marginHorizontal: 24,
        borderRadius: 24,
        padding: 20,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
        backdropFilter: "blur(10px)",
        alignItems: "center",
    },
    summaryLabel: {
        color: "rgba(255, 255, 255, 0.8)",
        fontSize: 14,
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 1,
        marginBottom: 8,
    },
    summaryAmount: {
        color: "white",
        fontSize: 36,
        fontWeight: "900",
        marginBottom: 4,
    },
    summaryStatus: {
        color: "white",
        fontSize: 14,
        fontWeight: "700",
        opacity: 0.9,
    },
    contentSheet: {
        flex: 1,
        backgroundColor: "white",
        borderTopLeftRadius: 36,
        borderTopRightRadius: 36,
        marginTop: -40,
        paddingTop: 32,
    },
    sectionTitleContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 24,
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: "#0f172a",
    },
    seeAllText: {
        fontSize: 14,
        fontWeight: "700",
        color: "#DAA520",
    },
    memberScroll: {
        paddingLeft: 24,
        paddingBottom: 24,
        marginBottom: 8,
    },
    memberCard: {
        backgroundColor: "#f8fafc",
        borderRadius: 20,
        padding: 12,
        marginRight: 12,
        width: 140,
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#f1f5f9",
    },
    memberAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: "#DAA520",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 10,
    },
    memberInitials: {
        color: "white",
        fontSize: 18,
        fontWeight: "800",
    },
    memberName: {
        fontSize: 14,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 4,
        textAlign: "center",
    },
    memberBalance: {
        fontSize: 12,
        fontWeight: "600",
    },
    expenseListHeader: {
        paddingHorizontal: 24,
        marginBottom: 16,
        marginTop: 8,
    },
    expenseList: {
        paddingHorizontal: 24,
        paddingBottom: 100,
    },
    expenseCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: 20,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#f1f5f9",
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.05,
                shadowRadius: 10,
            },
            android: {
                elevation: 3,
            },
        }),
    },
    expenseIconContainer: {
        width: 52,
        height: 52,
        borderRadius: 16,
        backgroundColor: "#fffbeb",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
    },
    expenseInfo: {
        flex: 1,
    },
    expenseTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 4,
    },
    expenseMeta: {
        fontSize: 13,
        color: "#64748b",
        fontWeight: "500",
    },
    expenseAmountContainer: {
        alignItems: "flex-end",
    },
    expenseAmount: {
        fontSize: 18,
        fontWeight: "800",
        color: "#0f172a",
    },
    expenseDate: {
        fontSize: 11,
        color: "#94a3b8",
        marginTop: 4,
        fontWeight: "600",
    },
    fab: {
        position: "absolute",
        bottom: 30,
        right: 24,
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: "#DAA520",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    },
    emptyState: {
        alignItems: "center",
        justifyContent: "center",
        paddingTop: 40,
        paddingHorizontal: 40,
    },
    emptyIconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "#f8fafc",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: "800",
        color: "#1e293b",
        marginBottom: 8,
    },
    emptyText: {
        fontSize: 14,
        color: "#64748b",
        textAlign: "center",
        lineHeight: 20,
    },
    modalContainer: {
        flex: 1,
        backgroundColor: "white",
    },
    modalHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
        paddingTop: Platform.OS === "ios" ? 60 : 40,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "900",
        color: "#0f172a",
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#f8fafc",
        justifyContent: "center",
        alignItems: "center",
    },
    membersList: {
        padding: 24,
    },
    memberListCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: 20,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    memberListInfo: {
        flex: 1,
    },
    memberListName: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 2,
    },
    memberListEmail: {
        fontSize: 13,
        color: "#64748b",
    },
    hostBadge: {
        backgroundColor: "#fffbeb",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#fef3c7",
    },
    hostBadgeText: {
        color: "#b45309",
        fontSize: 11,
        fontWeight: "700",
        textTransform: "uppercase",
    },
});
