import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        height: height * 0.25,
        justifyContent: "flex-start",
        paddingTop: Platform.OS === "ios" ? 60 : 40,
    },
    headerTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "900",
        color: "white",
        letterSpacing: 1,
        flex: 1,
        marginLeft: 16,
    },
    headerSubtitle: {
        fontSize: 13,
        color: "rgba(255, 255, 255, 0.9)",
        fontWeight: "600",
        marginHorizontal: 24,
        marginTop: 4,
        textTransform: "uppercase",
        letterSpacing: 1,
    },
    contentSheet: {
        flex: 1,
        backgroundColor: "white",
        borderTopLeftRadius: 36,
        borderTopRightRadius: 36,
        marginTop: -30,
        paddingTop: 32,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    inputContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        fontWeight: "700",
        color: "#64748b",
        marginBottom: 8,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#f1f5f9",
        paddingHorizontal: 16,
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        paddingVertical: 14,
        fontSize: 16,
        color: "#0f172a",
        fontWeight: "600",
    },
    amountWrapper: {
        backgroundColor: "#fffbeb",
        borderColor: "#fef3c7",
    },
    currencyText: {
        fontSize: 18,
        fontWeight: "800",
        color: "#DAA520",
        marginRight: 8,
    },
    amountInput: {
        fontSize: 24,
        fontWeight: "900",
        color: "#b45309",
    },
    textAreaWrapper: {
        alignItems: "flex-start",
        paddingTop: 12,
    },
    textArea: {
        height: 100,
        textAlignVertical: "top",
    },
    categoryGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 10,
        marginTop: 4,
    },
    categoryCard: {
        width: (width - 68) / 3,
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        padding: 12,
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#f1f5f9",
    },
    selectedCategoryCard: {
        backgroundColor: "#fffbeb",
        borderColor: "#DAA520",
    },
    categoryIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    categoryLabel: {
        fontSize: 11,
        fontWeight: "700",
        color: "#64748b",
        textAlign: "center",
    },
    selectedCategoryLabel: {
        color: "#DAA520",
    },
    footer: {
        padding: 24,
        backgroundColor: "white",
        borderTopWidth: 1,
        borderTopColor: "#f1f5f9",
    },
    submitButton: {
        backgroundColor: "#DAA520",
        height: 56,
        borderRadius: 18,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 6,
    },
    submitButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "800",
        letterSpacing: 1,
        marginLeft: 8,
    },
    submitButtonDisabled: {
        opacity: 0.6,
        shadowOpacity: 0.1,
    },
    errorText: {
        fontSize: 11,
        color: "#dc2626",
        fontWeight: "700",
        marginTop: 4,
        marginLeft: 4,
    },
});
