import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    keyboardAvoidingView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
    },
    header: {
        height: height * 0.28,
        justifyContent: "center",
        alignItems: "center",
        paddingTop: Platform.OS === "ios" ? 40 : 20,
    },
    iconComposition: {
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 16,
    },
    glassCircle: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: "rgba(255, 255, 255, 0.25)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "rgba(255, 255, 255, 0.45)",
    },
    headerTitle: {
        fontSize: 32,
        fontWeight: "900",
        color: "white",
        letterSpacing: 4,
        marginBottom: 4,
        textShadowColor: "rgba(0, 0, 0, 0.12)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
    },
    headerSubtitle: {
        fontSize: 12,
        color: "rgba(255, 255, 255, 0.95)",
        fontWeight: "600",
        letterSpacing: 1.5,
        textTransform: "uppercase",
    },
    contentSheet: {
        flex: 1,
        backgroundColor: "white",
        borderTopLeftRadius: 36,
        borderTopRightRadius: 36,
        marginTop: -30,
        paddingHorizontal: 24,
        paddingTop: 32,
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: -12 },
                shadowOpacity: 0.1,
                shadowRadius: 20,
            },
            android: {
                elevation: 12,
            },
        }),
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: "800",
        color: "#0f172a",
        marginBottom: 6,
    },
    sectionSubtitle: {
        fontSize: 15,
        color: "#64748b",
        marginBottom: 28,
    },
    inputContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 14,
        fontWeight: "700",
        color: "#475569",
        marginBottom: 10,
        marginLeft: 4,
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f8fafc",
        borderRadius: 18,
        borderWidth: 1.5,
        borderColor: "#f1f5f9",
        paddingHorizontal: 16,
    },
    inputWrapperError: {
        borderColor: "#fee2e2",
        backgroundColor: "#fffafb",
    },
    inputIcon: {
        marginRight: 12,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: "#0f172a",
        paddingVertical: 14,
        fontWeight: "500",
    },
    textArea: {
        height: 100,
        textAlignVertical: "top",
        paddingTop: 14,
    },
    helperText: {
        fontSize: 12,
        color: "#94a3b8",
        marginTop: 6,
        marginLeft: 4,
        lineHeight: 18,
    },
    infoBox: {
        flexDirection: "row",
        backgroundColor: "#f0f9ff",
        borderRadius: 18,
        padding: 16,
        marginTop: 8,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "#bae6fd",
    },
    infoIcon: {
        marginRight: 12,
        marginTop: 2,
    },
    infoText: {
        flex: 1,
        fontSize: 13,
        color: "#0369a1",
        lineHeight: 20,
        fontWeight: "500",
    },
    footerActions: {
        flexDirection: "row",
        paddingBottom: 40,
        marginTop: 12,
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 16,
        borderRadius: 18,
        alignItems: "center",
        backgroundColor: "#f1f5f9",
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    cancelButtonText: {
        color: "#64748b",
        fontSize: 16,
        fontWeight: "700",
    },
    createButton: {
        flex: 2,
        paddingVertical: 16,
        borderRadius: 18,
        alignItems: "center",
        backgroundColor: "#DAA520",
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    createButtonDisabled: {
        opacity: 0.6,
        backgroundColor: "#cbd5e1",
        shadowOpacity: 0,
    },
    createButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "800",
        letterSpacing: 0.5,
    },
});
