import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    background: {
        flex: 1,
    },
    keyboardAvoidingView: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
    },
    header: {
        height: height * 0.28,
        justifyContent: "center",
        alignItems: "center",
        paddingTop: Platform.OS === "ios" ? 40 : 20,
    },
    iconComposition: {
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 20,
    },
    glassCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: "rgba(255, 255, 255, 0.25)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.4)",
    },
        logoCircle: {
        width: 80,
        height: 80,
        borderRadius: 20,
    backgroundColor: "#fffbeb",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#DAA520",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 10,
    transform: [{ rotate: '45deg' }],
  },
  logoSection: {
    alignItems: "center",
        marginVertical: 24,
  },
  appName: {
        fontSize: 24,
    fontWeight: "900",
    color: "#ffffffff",
        marginTop: 20,
    letterSpacing: 2,
  },
  appTagline: {
        fontSize: 12,
    color: "#000000ff",
    fontWeight: "600",
    marginTop: 4,
  },
imageContainer: {
        width: width * 0.6,
        height: width * 0.6,
        maxWidth: 240,
        maxHeight: 240,
    justifyContent: "center",
    alignItems: "center",
  },
    headerTitle: {
        fontSize: 28,
        fontWeight: "900",
        color: "white",
        letterSpacing: 6,
        marginBottom: 4,
        textShadowColor: "rgba(0, 0, 0, 0.1)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    headerSubtitle: {
        fontSize: 11,
        color: "rgba(255, 255, 255, 0.95)",
        fontWeight: "600",
        letterSpacing: 2,
        textTransform: "uppercase",
    },
    contentSheet: {
        flex: 1,
        backgroundColor: "white",
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        marginTop: -20,
        paddingHorizontal: 32,
        paddingTop: 32,
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: -12 },
                shadowOpacity: 0.1,
                shadowRadius: 20,
            },
            android: {
                elevation: 12,
            },
        }),
    },
    welcomeText: {
        fontSize: 22,
        fontWeight: "800",
        color: "#0f172a",
        marginBottom: 4,
    },
    instructionText: {
        fontSize: 14,
        color: "#64748b",
        marginBottom: 20,
    },
    inputContainer: {
        marginBottom: 12,
    },
    label: {
        fontSize: 14,
        fontWeight: "700",
        color: "#475569",
        marginBottom: 6,
        marginLeft: 4,
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#f1f5f9",
        paddingHorizontal: 20,
        height: 52,
    },
    inputWrapperError: {
        borderColor: "#fee2e2",
        backgroundColor: "#fffafb",
    },
    inputIcon: {
        marginRight: 14,
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: "#0f172a",
        height: "100%",
        fontWeight: "500",
    },
    eyeIcon: {
        padding: 4,
    },
    signupButton: {
        backgroundColor: "#DAA520",
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: "center",
        marginTop: 12,
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 8,
    },
    signupButtonDisabled: {
        opacity: 0.7,
    },
    signupButtonText: {
        color: "white",
        fontSize: 18,
        fontWeight: "800",
        letterSpacing: 0.5,
    },
    footer: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 20,
        paddingBottom: 32,
    },
    footerText: {
        color: "#94a3b8",
        fontSize: 16,
        fontWeight: "500",
    },
    loginText: {
        color: "#DAA520",
        fontWeight: "700",
        fontSize: 16,
    },
    errorText: {
        color: "#ef4444",
        fontSize: 13,
        marginTop: 8,
        marginLeft: 8,
        fontWeight: "600",
    },
    generalErrorContainer: {
        backgroundColor: "#fff1f2",
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "#fecaca",
    },
    generalErrorText: {
        color: "#be123c",
        textAlign: "center",
        fontSize: 14,
        fontWeight: "600",
    },
});
