import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    background: {
        flex: 1,
    },
    header: {
        height: height * 0.34,
        justifyContent: "center",
        alignItems: "center",
        paddingTop: Platform.OS === "ios" ? 40 : 20,
    },
    iconComposition: {
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 20,
    },
    glassCircle: {
        width: 84,
        height: 84,
        borderRadius: 42,
        backgroundColor: "rgba(255, 255, 255, 0.25)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "rgba(255, 255, 255, 0.45)",
    },
    logoCircle: {
    width: 100,
    height: 100,
    borderRadius: 30,
    backgroundColor: "#fffbeb",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#DAA520",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 10,
    transform: [{ rotate: '45deg' }],
  },
  logoSection: {
    alignItems: "center",
    marginVertical: 40,
  },
  appName: {
    fontSize: 28,
    fontWeight: "900",
    color: "#ffffffff",
    marginTop: 30,
    letterSpacing: 2,
  },
  appTagline: {
    fontSize: 14,
    color: "#000000ff",
    fontWeight: "600",
    marginTop: 4,
  },
imageContainer: {
    width: width * 0.7,
    height: width * 0.7,
    maxWidth: 280,
    maxHeight: 280,
    justifyContent: "center",
    alignItems: "center",
  },
    headerTitle: {
        fontSize: 36,
        fontWeight: "900",
        color: "white",
        letterSpacing: 6,
        marginBottom: 6,
        textShadowColor: "rgba(0, 0, 0, 0.12)",
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
    },
    headerSubtitle: {
        fontSize: 14,
        color: "rgba(255, 255, 255, 0.95)",
        fontWeight: "600",
        letterSpacing: 2,
        textTransform: "uppercase",
    },
    contentSheet: {
        flex: 1,
        backgroundColor: "white",
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        marginTop: -20,
        paddingHorizontal: 32,
        paddingTop: 32,
        alignItems: "center",
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: -12 },
                shadowOpacity: 0.12,
                shadowRadius: 20,
            },
            android: {
                elevation: 12,
            },
        }),
    },
    title: {
        fontSize: 30,
        fontWeight: "800",
        color: "#0f172a",
        marginBottom: 8,
        textAlign: "center",
    },
    subtitle: {
        fontSize: 17,
        color: "#64748b",
        textAlign: "center",
        marginBottom: 8,
    },
    email: {
        fontSize: 18,
        fontWeight: "700",
        color: "#DAA520",
        textAlign: "center",
        marginBottom: 24,
    },
    description: {
        fontSize: 17,
        color: "#64748b",
        textAlign: "center",
        lineHeight: 22,
        marginBottom: 24,
    },
    successMessage: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f0fdf4",
        borderRadius: 16,
        padding: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "#bbf7d0",
    },
    successText: {
        color: "#166534",
        fontSize: 17,
        fontWeight: "700",
        marginLeft: 10,
    },
    primaryButton: {
        backgroundColor: "#DAA520",
        borderRadius: 16,
        paddingVertical: 16,
        width: "100%",
        alignItems: "center",
        marginBottom: 16,
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.35,
        shadowRadius: 12,
        elevation: 8,
    },
    primaryButtonText: {
        color: "white",
        fontSize: 18,
        fontWeight: "800",
        letterSpacing: 0.5,
    },
    secondaryButton: {
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        paddingVertical: 14,
        width: "100%",
        alignItems: "center",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
    },
    secondaryButtonText: {
        color: "#64748b",
        fontSize: 16,
        fontWeight: "700",
    },
    buttonDisabled: {
        opacity: 0.6,
    },
    footerStatus: {
        marginTop: 20,
        paddingBottom: 32,
        alignItems: "center",
    },
    backToLoginText: {
        color: "#DAA520",
        fontWeight: "700",
        fontSize: 16,
        textDecorationLine: "none",
    },
});
