import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        height: height * 0.28,
        justifyContent: "flex-start",
        paddingTop: Platform.OS === "ios" ? 60 : 40,
    },
    headerTop: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.3)",
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "900",
        color: "white",
        letterSpacing: 1,
        flex: 1,
        marginLeft: 16,
    },
    headerSubtitle: {
    fontSize: 24,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "600",
    marginHorizontal: 24,
    marginTop: 20,
    textAlign: "center",
    },
    tabsContainer: {
        backgroundColor: "white",
        borderTopLeftRadius: 36,
        borderTopRightRadius: 36,
        marginTop: -30,
        paddingTop: 20,
        paddingHorizontal: 12,
        flexDirection: "row",
        justifyContent: "space-around",
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    tabButton: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        alignItems: "center",
        minWidth: 80,
    },
    activeTabButton: {
        backgroundColor: "#fffbeb",
    },
    tabLabel: {
        fontSize: 12,
        fontWeight: "700",
        color: "#64748b",
        marginTop: 4,
    },
    activeTabLabel: {
        color: "#DAA520",
    },
    contentContainer: {
        flex: 1,
        backgroundColor: "white",
    },
    scrollContent: {
        paddingTop: 12,
        paddingBottom: 40,
    },
    section: {
        paddingHorizontal: 20,
        marginBottom: 24,
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: "#0f172a",
    },
    statsGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: 12,
    },
    statBox: {
        width: (width - 52) / 2,
        backgroundColor: "#f8fafc",
        borderRadius: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    statLabel: {
        fontSize: 12,
        color: "#64748b",
        fontWeight: "600",
        textTransform: "uppercase",
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    statValue: {
        fontSize: 20,
        fontWeight: "800",
        color: "#0f172a",
    },
    statIconContainer: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 12,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    listCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: 20,
        padding: 14,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#f1f5f9",
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 4 },
                shadowOpacity: 0.03,
                shadowRadius: 8,
            },
            android: {
                elevation: 2,
            },
        }),
    },
    listIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: "#f8fafc",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 14,
    },
    listContent: {
        flex: 1,
    },
    listTitle: {
        fontSize: 15,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 2,
    },
    listSubtitle: {
        fontSize: 12,
        color: "#64748b",
        fontWeight: "500",
    },
    listValue: {
        fontSize: 16,
        fontWeight: "800",
        color: "#0f172a",
    },
    balanceCard: {
        backgroundColor: "white",
        borderRadius: 24,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#f1f5f9",
        ...Platform.select({
            ios: {
                shadowColor: "#000",
                shadowOffset: { width: 0, height: 6 },
                shadowOpacity: 0.05,
                shadowRadius: 10,
            },
            android: {
                elevation: 3,
            },
        }),
    },
    balanceHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
    },
    balanceAvatar: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: "#DAA520",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    balanceInitials: {
        color: "white",
        fontSize: 18,
        fontWeight: "800",
    },
    balanceName: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1e293b",
    },
    balanceBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        backgroundColor: "#f1f5f9",
        marginTop: 4,
        alignSelf: "flex-start",
    },
    balanceBadgeText: {
        fontSize: 10,
        fontWeight: "700",
        color: "#64748b",
        textTransform: "uppercase",
    },
    balanceStats: {
        flexDirection: "row",
        borderTopWidth: 1,
        borderTopColor: "#f1f5f9",
        paddingTop: 16,
        justifyContent: "space-between",
    },
    balanceStatItem: {
        flex: 1,
        alignItems: "center",
    },
    balanceStatDivider: {
        width: 1,
        height: "100%",
        backgroundColor: "#f1f5f9",
    },
    balanceStatLabel: {
        fontSize: 10,
        color: "#94a3b8",
        fontWeight: "700",
        textTransform: "uppercase",
        marginBottom: 4,
    },
    balanceStatValue: {
        fontSize: 15,
        fontWeight: "800",
        color: "#0f172a",
    },
    settlementCard: {
        backgroundColor: "#fffbeb",
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#fef3c7",
    },
    settlementFlow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 16,
    },
    settlementUser: {
        alignItems: "center",
        flex: 1,
    },
    settlementArrow: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#DAA520",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    settlementAmountBox: {
        backgroundColor: "white",
        borderRadius: 16,
        paddingVertical: 10,
        paddingHorizontal: 20,
        alignItems: "center",
    },
    settlementLabel: {
        fontSize: 9,
        color: "#92400e",
        fontWeight: "700",
        textTransform: "uppercase",
        marginBottom: 2,
    },
    settlementAmount: {
        fontSize: 22,
        fontWeight: "900",
        color: "#b45309",
    },
    emptyState: {
        paddingTop: 60,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: "#1e293b",
        marginTop: 16,
        marginBottom: 8,
    },
    emptyText: {
        fontSize: 14,
        color: "#64748b",
        textAlign: "center",
        lineHeight: 20,
        paddingHorizontal: 40,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "white",
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        fontWeight: "600",
        color: "#DAA520",
    },
});
