import { Dimensions, Platform, StyleSheet } from "react-native";

const { height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        height: height * 0.3,
        justifyContent: "center",
        alignItems: "center",
        paddingTop: Platform.OS === "ios" ? 40 : 20,
    },
    profileImageContainer: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 10,
        borderWidth: 4,
        borderColor: "rgba(255, 255, 255, 0.4)",
    },
    avatarText: {
        fontSize: 40,
        fontWeight: "900",
        color: "#DAA520",
    },
    avatarImage: {
        width: "100%",
        height: "100%",
        borderRadius: 50,
    },
    userName: {
        fontSize: 24,
        fontWeight: "900",
        color: "white",
        marginTop: 16,
        letterSpacing: 0.5,
    },
    userEmail: {
        fontSize: 14,
        color: "rgba(255, 255, 255, 0.9)",
        fontWeight: "600",
        marginTop: 4,
    },
    userBio: {
        fontSize: 13,
        color: "rgba(255, 255, 255, 0.8)",
        fontWeight: "500",
        marginTop: 8,
        maxWidth: "80%",
        textAlign: "center",
        fontStyle: "italic",
    },
    contentSheet: {
        flex: 1,
        backgroundColor: "white",
        borderTopLeftRadius: 36,
        borderTopRightRadius: 36,
        marginTop: -30,
        paddingTop: 32,
    },
    scrollContent: {
        paddingHorizontal: 24,
        paddingBottom: 40,
    },
    section: {
        marginBottom: 32,
    },
    sectionTitle: {
        fontSize: 14,
        fontWeight: "800",
        color: "#94a3b8",
        textTransform: "uppercase",
        letterSpacing: 1.5,
        marginBottom: 16,
        marginLeft: 4,
    },
    menuItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 20,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: "#f1f5f9",
    },
    menuIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    menuText: {
        flex: 1,
        fontSize: 16,
        fontWeight: "700",
        color: "#0f172a",
    },
    chevron: {
        marginLeft: 8,
    },
    logoutButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff1f2",
        padding: 18,
        borderRadius: 20,
        marginTop: 8,
        borderWidth: 1,
        borderColor: "#ffe4e6",
    },
    logoutIcon: {
        marginRight: 12,
    },
    logoutText: {
        fontSize: 16,
        fontWeight: "800",
        color: "#e11d48",
        letterSpacing: 0.5,
    },
    versionText: {
        textAlign: "center",
        color: "#cbd5e1",
        fontSize: 12,
        fontWeight: "600",
        marginTop: 20,
    },
});
